# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_wifi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WIFI(object):
    def setupUi(self, WIFI):
        WIFI.setObjectName("WIFI")
        WIFI.resize(377, 432)
        self.cmd_ping = QtWidgets.QPushButton(WIFI)
        self.cmd_ping.setGeometry(QtCore.QRect(140, 150, 93, 28))
        self.cmd_ping.setObjectName("cmd_ping")
        self.ip_info = QtWidgets.QLineEdit(WIFI)
        self.ip_info.setGeometry(QtCore.QRect(130, 40, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ip_info.setFont(font)
        self.ip_info.setObjectName("ip_info")
        self.label = QtWidgets.QLabel(WIFI)
        self.label.setGeometry(QtCore.QRect(70, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(WIFI)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cmd_ipconfig = QtWidgets.QPushButton(WIFI)
        self.cmd_ipconfig.setGeometry(QtCore.QRect(10, 150, 93, 28))
        self.cmd_ipconfig.setObjectName("cmd_ipconfig")
        self.cmd_save = QtWidgets.QPushButton(WIFI)
        self.cmd_save.setGeometry(QtCore.QRect(270, 150, 93, 28))
        self.cmd_save.setObjectName("cmd_save")
        self.port_info = QtWidgets.QLineEdit(WIFI)
        self.port_info.setGeometry(QtCore.QRect(130, 90, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.port_info.setFont(font)
        self.port_info.setText("")
        self.port_info.setObjectName("port_info")
        self.show_res = QtWidgets.QTextBrowser(WIFI)
        self.show_res.setGeometry(QtCore.QRect(10, 190, 351, 221))
        self.show_res.setObjectName("show_res")

        self.retranslateUi(WIFI)
        self.cmd_ipconfig.clicked.connect(WIFI.ip_config)
        self.cmd_ping.clicked.connect(WIFI.ping)
        self.cmd_save.clicked.connect(WIFI.config_ok)
        QtCore.QMetaObject.connectSlotsByName(WIFI)

    def retranslateUi(self, WIFI):
        _translate = QtCore.QCoreApplication.translate
        WIFI.setWindowTitle(_translate("WIFI", "config_wifi"))
        self.cmd_ping.setText(_translate("WIFI", "ping"))
        self.ip_info.setInputMask(_translate("WIFI", "000.000.000.000;_"))
        self.ip_info.setText(_translate("WIFI", "..."))
        self.label.setText(_translate("WIFI", "ip:"))
        self.label_2.setText(_translate("WIFI", "port:"))
        self.cmd_ipconfig.setText(_translate("WIFI", "ipconfig"))
        self.cmd_save.setText(_translate("WIFI", "save"))
        self.port_info.setInputMask(_translate("WIFI", "9999;_"))
