# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_serial.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SERIAL(object):
    def setupUi(self, SERIAL):
        SERIAL.setObjectName("SERIAL")
        SERIAL.resize(350, 516)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SERIAL.sizePolicy().hasHeightForWidth())
        SERIAL.setSizePolicy(sizePolicy)
        self.save_serial = QtWidgets.QPushButton(SERIAL)
        self.save_serial.setGeometry(QtCore.QRect(170, 450, 100, 35))
        self.save_serial.setObjectName("save_serial")
        self.verticalLayoutWidget = QtWidgets.QWidget(SERIAL)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 71, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(40)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(SERIAL)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(170, 40, 101, 391))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.serial_select = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_select.sizePolicy().hasHeightForWidth())
        self.serial_select.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.serial_select.setFont(font)
        self.serial_select.setObjectName("serial_select")
        self.serial_select.addItem("")
        self.serial_select.addItem("")
        self.serial_select.addItem("")
        self.verticalLayout_2.addWidget(self.serial_select)
        self.serial_baudrate = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_baudrate.sizePolicy().hasHeightForWidth())
        self.serial_baudrate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.serial_baudrate.setFont(font)
        self.serial_baudrate.setObjectName("serial_baudrate")
        self.serial_baudrate.addItem("")
        self.serial_baudrate.addItem("")
        self.serial_baudrate.addItem("")
        self.serial_baudrate.addItem("")
        self.verticalLayout_2.addWidget(self.serial_baudrate)
        self.serial_databits = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_databits.sizePolicy().hasHeightForWidth())
        self.serial_databits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.serial_databits.setFont(font)
        self.serial_databits.setObjectName("serial_databits")
        self.serial_databits.addItem("")
        self.serial_databits.addItem("")
        self.serial_databits.addItem("")
        self.verticalLayout_2.addWidget(self.serial_databits)
        self.serial_parity = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_parity.sizePolicy().hasHeightForWidth())
        self.serial_parity.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.serial_parity.setFont(font)
        self.serial_parity.setObjectName("serial_parity")
        self.serial_parity.addItem("")
        self.verticalLayout_2.addWidget(self.serial_parity)
        self.serial_stopbits = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_stopbits.sizePolicy().hasHeightForWidth())
        self.serial_stopbits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.serial_stopbits.setFont(font)
        self.serial_stopbits.setObjectName("serial_stopbits")
        self.serial_stopbits.addItem("")
        self.verticalLayout_2.addWidget(self.serial_stopbits)
        self.serial_detect = QtWidgets.QPushButton(SERIAL)
        self.serial_detect.setGeometry(QtCore.QRect(40, 450, 100, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_detect.sizePolicy().hasHeightForWidth())
        self.serial_detect.setSizePolicy(sizePolicy)
        self.serial_detect.setObjectName("serial_detect")

        self.retranslateUi(SERIAL)
        self.serial_detect.clicked.connect(SERIAL.detect_serial_fun)
        self.save_serial.clicked.connect(SERIAL.config_ok)
        QtCore.QMetaObject.connectSlotsByName(SERIAL)

    def retranslateUi(self, SERIAL):
        _translate = QtCore.QCoreApplication.translate
        SERIAL.setWindowTitle(_translate("SERIAL", "config_serial"))
        self.save_serial.setText(_translate("SERIAL", "保存"))
        self.label_2.setText(_translate("SERIAL", "串口选择:"))
        self.label_3.setText(_translate("SERIAL", "波特率:"))
        self.label_4.setText(_translate("SERIAL", "数据位:"))
        self.label_5.setText(_translate("SERIAL", "校验位:"))
        self.label_6.setText(_translate("SERIAL", "停止位:"))
        self.serial_select.setItemText(0, _translate("SERIAL", "com1"))
        self.serial_select.setItemText(1, _translate("SERIAL", "com2"))
        self.serial_select.setItemText(2, _translate("SERIAL", "com3"))
        self.serial_baudrate.setItemText(0, _translate("SERIAL", "115200"))
        self.serial_baudrate.setItemText(1, _translate("SERIAL", "9600"))
        self.serial_baudrate.setItemText(2, _translate("SERIAL", "19200"))
        self.serial_baudrate.setItemText(3, _translate("SERIAL", "57600"))
        self.serial_databits.setItemText(0, _translate("SERIAL", "8"))
        self.serial_databits.setItemText(1, _translate("SERIAL", "9"))
        self.serial_databits.setItemText(2, _translate("SERIAL", "10"))
        self.serial_parity.setItemText(0, _translate("SERIAL", "N"))
        self.serial_stopbits.setItemText(0, _translate("SERIAL", "1"))
        self.serial_detect.setText(_translate("SERIAL", "串口检测"))
